server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://<YOUR_DATABASE_URL>:5432/ecommerce
    username: <YOUR_DB_USERNAME>
    password: <YOUR_DB_PASSWORD>
    driver-class-name: org.postgresql.Driver  # Optional in latest Spring Boot, but safe to include.

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

