server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://<YOUR_DATABASE_URL>:3306/ecommerce
    username: <YOUR_DB_USERNAME>
    password: <YOUR_DB_PASSWORD>
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
